export const ROOM_SIZE_METERS = 10
export const INITIAL_LIGHT_DISTANCE_METERS = 2.4
export const MIN_LIGHT_HEIGHT_METERS = 1.25
export const MAX_LIGHT_HEIGHT_METERS = 2
export const EXIT_DOOR_WIDTH_METERS = 1.3
export const EXIT_DOOR_HEIGHT_METERS = 2.2
export const EXIT_DOOR_WALL_OFFSET_METERS = 0.035
export const EXIT_DOOR_FORWARD_OFFSET_METERS = 1.35

export const TRANSCRIPT_INACTIVITY_MS = 30_000
export const PANEL_ANIMATION_MS = 250
export const TRANSCRIPT_ANIMATION_MS = PANEL_ANIMATION_MS
export const FOREGROUND_PANEL_DWELL_MS = 60_000
export const PANEL_DEPTH_METERS = 0.015
export const PANEL_INITIAL_SIZE_METERS = 0.1
export const PANEL_FORCE_DISMISS_MS = 125
export const MAX_VISIBLE_PANELS = 8
export const MAX_PANEL_OUTPUT_CHARS = 32_000
export const MAX_PANEL_CANVAS_EDGE = 2_048
export const BACKGROUND_TERMINAL_POLL_MS = 2_000

export const LIGHT_SCALE_EXCURSION = 0.2
export const LIGHT_INTENSITY_EXCURSION = 0.045
export const REDUCED_LIGHT_SCALE_EXCURSION = 0.055
export const REDUCED_LIGHT_INTENSITY_EXCURSION = 0.018
